import Joi from 'joi';
import Regex from '../constants/regex.constant';

class agencyValidation {
    public agency = Joi.object({
        agencyName: Joi.string(),
        accountNumber: Joi.number(),
        companyName: Joi.string().required(),
        doingBusinessAs: Joi.string().required(),
        taxId: Joi.string(),
        phone: Joi.string(),
        fax: Joi.string().allow(''),
        address: Joi.string(),
        streetAddress: Joi.string(),
        city: Joi.string(),
        mailingAddressStateCode: Joi.string(),
        state: Joi.string(),
        mailingAddressCountry: Joi.string(),
        postalCode: Joi.string(),
        contactFirstName: Joi.string(),
        contactLastName: Joi.string(),
        // contactEmail: Joi.string(),
        contactMobileNumber: Joi.string(),
        contactOfficePhone: Joi.string(),
        accreditation: Joi.string(),
        agencyAdminEmail: Joi.string(),
        agencyAdminFirstName: Joi.string(),
        agencyAdminLastName: Joi.string(),
        agencyAdminMobile: Joi.string(),
        agencyOperationalStatus: Joi.string(),
        agencySubmissionStatus: Joi.string(),
        billingAddressCity: Joi.string(),
        billingAddressLine1: Joi.string(),
        billingAddressLine2: Joi.string().allow(''),
        billingAddressStateName: Joi.string(),
        billingAddressZipCode: Joi.string(),
        companyType: Joi.string(),
        email: Joi.string(),
        medicareProviderNo: Joi.string(),
        npi: Joi.string(),
        stateHhaLicenseNo: Joi.string(),
        submitterId: Joi.string(),
        subscriptionPlanId: Joi.string(),
        agencyShortCode: Joi.string(),
        billingAddressAreaCode: Joi.string(),
        hiqAdminComment: Joi.string().allow(''),
        comments: Joi.string().allow(''),
        baaEnvelopeId: Joi.string(),
        baaEnvelopeSentDate: Joi.string(),
        baaEnvelopeStatus: Joi.string(),
        discountId: Joi.string(),
        // websiteInfo: Joi.string().allow(''),
        contactPerson1Branch: Joi.string().allow(''),
        contactPerson1Email: Joi.string(),
        contactPerson1Name: Joi.string(),
        contactPerson1Phone: Joi.string(),
        contactPerson1Title: Joi.string(),
        contactPerson2Branch: Joi.string(),
        contactPerson2Email: Joi.string(),
        contactPerson2Name: Joi.string(),
        contactPerson2Phone: Joi.string(),
        contactPerson2Title: Joi.string(),
        contactPerson3Branch: Joi.string(),
        contactPerson3Email: Joi.string(),
        contactPerson3Name: Joi.string(),
        contactPerson3Phone: Joi.string(),
        contactPerson3Title: Joi.string(),
        demoRequestId: Joi.string().alphanum().max(30),
        agencyId: Joi.string(),
    })
}

export default agencyValidation;